version: '3.8'
services:

  mysql:
    image: mysql:latest
    container_name: mysql-e-commerce
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: e-commerce-project
      MYSQL_USER: e-commerce-user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-broker-e-commerce
    container_name: kafka
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9000:8080
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: e-commerce-project-kafka-ui
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  naming-server:
    image: e-commerce-project/naming-server
    build:
      context: ./naming-server
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8761
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    ports:
      - "8761:8761"

  api-gateway:
    image: e-commerce-project/api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8765
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SPRING_APPLICATION_NAME=api-gateway
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - naming-server
    ports:
      - "8765:8765"

  identity-service:
    image: e-commerce-project/identity-service
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SERVER_PORT=9898
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/e-commerce-project?createDatabaseIfNotExist=true&autoReconnect=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - naming-server
    ports:
      - "9898:9898"

  basket-service:
    image: e-commerce-project/basket-service
    build:
      context: ./basket-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SERVER_PORT=8400
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/e-commerce-project?createDatabaseIfNotExist=true&autoReconnect=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - naming-server
    ports:
      - "8400:8400"

  order-service:
    image: e-commerce-project/order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SERVER_PORT=8300
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/e-commerce-project?createDatabaseIfNotExist=true&autoReconnect=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - naming-server
    ports:
      - "8300:8300"

  product-service:
    image: e-commerce-project/product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SERVER_PORT=8000
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/e-commerce-project?createDatabaseIfNotExist=true&autoReconnect=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - naming-server
    ports:
      - "8000:8000"

  wallet-service:
    image: e-commerce-project/wallet-service
    build:
      context: ./wallet-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SERVER_PORT=8005
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/e-commerce-project?createDatabaseIfNotExist=true&autoReconnect=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - naming-server
    ports:
      - "8005:8005"

  logger-service:
    image: e-commerce-project/logger-service
    build:
      context: ./logger-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka/
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/e-commerce-project?createDatabaseIfNotExist=true&autoReconnect=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - naming-server
      - kafka
      - zookeeper
    ports:
      - "8083:8083"
